// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewExpenseImport } from './routes/new-expense'
import { Route as AllExpensesImport } from './routes/all-expenses'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NewExpenseRoute = NewExpenseImport.update({
  path: '/new-expense',
  getParentRoute: () => rootRoute,
} as any)

const AllExpensesRoute = AllExpensesImport.update({
  path: '/all-expenses',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/all-expenses': {
      preLoaderRoute: typeof AllExpensesImport
      parentRoute: typeof rootRoute
    }
    '/new-expense': {
      preLoaderRoute: typeof NewExpenseImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  AllExpensesRoute,
  NewExpenseRoute,
])
